"""initial funnel schema

Revision ID: ee38e13223f4
Revises: 
Create Date: 2026-06-29 23:41:07.505282

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ee38e13223f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.create_index(op.f('ix_admin_users_id'), 'admin_users', ['id'], unique=False)
    op.create_table('gift_campaigns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('gift_ids', sa.JSON(), nullable=True),
    sa.Column('email_subject', sa.Text(), server_default='', nullable=False),
    sa.Column('email_html', sa.Text(), server_default='', nullable=False),
    sa.Column('audience_config', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='draft', nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_recipients', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sent_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('failed_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('skipped_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gift_campaigns_id'), 'gift_campaigns', ['id'], unique=False)
    op.create_index('ix_gift_campaigns_status', 'gift_campaigns', ['status'], unique=False)
    op.create_table('gifts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('internal_config', sa.JSON(), nullable=True),
    sa.Column('external_items', sa.JSON(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gifts_id'), 'gifts', ['id'], unique=False)
    op.create_table('site_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_settings_id'), 'site_settings', ['id'], unique=False)
    op.create_index(op.f('ix_site_settings_key'), 'site_settings', ['key'], unique=True)
    op.create_table('discounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('discount_type', sa.String(length=20), nullable=False),
    sa.Column('discount_value', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_redemptions', sa.Integer(), nullable=True),
    sa.Column('redeemed_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_discounts_code')
    )
    op.create_index(op.f('ix_discounts_code'), 'discounts', ['code'], unique=False)
    op.create_index(op.f('ix_discounts_id'), 'discounts', ['id'], unique=False)
    op.create_index(op.f('ix_discounts_is_active'), 'discounts', ['is_active'], unique=False)
    op.create_table('email_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scope', sa.String(length=50), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('template_key', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('subject', sa.Text(), server_default='', nullable=False),
    sa.Column('html_body', sa.Text(), server_default='', nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['admin_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope', 'owner_id', 'template_key', name='uq_email_template_scope_owner_key')
    )
    op.create_index(op.f('ix_email_templates_id'), 'email_templates', ['id'], unique=False)
    op.create_index('ix_email_templates_scope_owner', 'email_templates', ['scope', 'owner_id'], unique=False)
    op.create_table('gift_grants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('gift_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('recipient_name', sa.String(length=255), nullable=True),
    sa.Column('recipient_phone', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('external_items_snapshot', sa.JSON(), nullable=True),
    sa.Column('granted_by', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='granted', nullable=False),
    sa.Column('email_status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('email_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_error', sa.Text(), nullable=True),
    sa.Column('email_subject_snapshot', sa.Text(), nullable=True),
    sa.Column('email_html_snapshot', sa.Text(), nullable=True),
    sa.Column('resend_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_resend_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gift_id'], ['gifts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gift_id', 'email', name='uq_gift_grants_gift_email')
    )
    op.create_index('ix_gift_grants_email', 'gift_grants', ['email'], unique=False)
    op.create_index('ix_gift_grants_email_status', 'gift_grants', ['email_status'], unique=False)
    op.create_index(op.f('ix_gift_grants_gift_id'), 'gift_grants', ['gift_id'], unique=False)
    op.create_index(op.f('ix_gift_grants_id'), 'gift_grants', ['id'], unique=False)
    op.create_table('media_assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('object_key', sa.String(length=1024), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('kind', sa.String(length=20), server_default='other', nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('original_filename', sa.String(length=512), nullable=True),
    sa.Column('uploaded_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['admin_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_assets_id'), 'media_assets', ['id'], unique=False)
    op.create_index(op.f('ix_media_assets_kind'), 'media_assets', ['kind'], unique=False)
    op.create_index(op.f('ix_media_assets_object_key'), 'media_assets', ['object_key'], unique=True)
    op.create_index(op.f('ix_media_assets_uploaded_by'), 'media_assets', ['uploaded_by'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_price', sa.Integer(), server_default='0', nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='draft', nullable=False),
    sa.Column('thumbnail_url', sa.String(length=1024), nullable=True),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=True)
    op.create_index(op.f('ix_products_source_id'), 'products', ['source_id'], unique=False)
    op.create_index(op.f('ix_products_status'), 'products', ['status'], unique=False)
    op.create_index(op.f('ix_products_type'), 'products', ['type'], unique=False)
    op.create_table('url_redirects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_path', sa.String(length=500), nullable=False),
    sa.Column('target_url', sa.String(length=1024), nullable=False),
    sa.Column('match_type', sa.String(length=20), server_default='exact', nullable=False),
    sa.Column('status_code', sa.Integer(), server_default='301', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_url_redirects_id'), 'url_redirects', ['id'], unique=False)
    op.create_index(op.f('ix_url_redirects_is_active'), 'url_redirects', ['is_active'], unique=False)
    op.create_index(op.f('ix_url_redirects_source_path'), 'url_redirects', ['source_path'], unique=True)
    op.create_table('discount_default_activations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('discount_id', sa.String(length=36), nullable=False),
    sa.Column('owner_type', sa.String(length=20), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['discount_id'], ['discounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discount_id', 'owner_type', 'owner_id', name='uq_dda_discount_owner')
    )
    op.create_index(op.f('ix_discount_default_activations_discount_id'), 'discount_default_activations', ['discount_id'], unique=False)
    op.create_index(op.f('ix_discount_default_activations_id'), 'discount_default_activations', ['id'], unique=False)
    op.create_index(op.f('ix_discount_default_activations_owner_id'), 'discount_default_activations', ['owner_id'], unique=False)
    op.create_table('discount_scopes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('discount_id', sa.String(length=36), nullable=False),
    sa.Column('owner_type', sa.String(length=20), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['discount_id'], ['discounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discount_id', 'owner_type', 'owner_id', name='uq_discount_scope_owner')
    )
    op.create_index(op.f('ix_discount_scopes_discount_id'), 'discount_scopes', ['discount_id'], unique=False)
    op.create_index(op.f('ix_discount_scopes_id'), 'discount_scopes', ['id'], unique=False)
    op.create_index(op.f('ix_discount_scopes_owner_id'), 'discount_scopes', ['owner_id'], unique=False)
    op.create_table('funnels',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='draft', nullable=False),
    sa.Column('currency', sa.String(length=10), server_default='VND', nullable=False),
    sa.Column('checkout_config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('success_config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('zalo_link', sa.String(length=1024), nullable=True),
    sa.Column('variables', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('variables_meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('tracking_config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('capture_token', sa.String(length=48), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funnels_capture_token'), 'funnels', ['capture_token'], unique=True)
    op.create_index(op.f('ix_funnels_id'), 'funnels', ['id'], unique=False)
    op.create_index(op.f('ix_funnels_product_id'), 'funnels', ['product_id'], unique=False)
    op.create_index(op.f('ix_funnels_slug'), 'funnels', ['slug'], unique=True)
    op.create_index(op.f('ix_funnels_status'), 'funnels', ['status'], unique=False)
    op.create_table('order_discounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_type', sa.String(length=20), server_default='funnel', nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('discount_id', sa.String(length=36), nullable=False),
    sa.Column('applied_percent', sa.Integer(), server_default='0', nullable=False),
    sa.Column('applied_amount', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['discount_id'], ['discounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_type', 'order_id', 'discount_id', name='uq_order_discounts_type_order_discount')
    )
    op.create_index(op.f('ix_order_discounts_discount_id'), 'order_discounts', ['discount_id'], unique=False)
    op.create_index(op.f('ix_order_discounts_id'), 'order_discounts', ['id'], unique=False)
    op.create_index(op.f('ix_order_discounts_order_id'), 'order_discounts', ['order_id'], unique=False)
    op.create_table('broadcast_campaigns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('origin', sa.String(length=16), nullable=False),
    sa.Column('funnel_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('html_body', sa.Text(), nullable=False),
    sa.Column('audience_config', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='draft', nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_recipients', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sent_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('failed_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['funnel_id'], ['funnels.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broadcast_campaigns_funnel_id'), 'broadcast_campaigns', ['funnel_id'], unique=False)
    op.create_index(op.f('ix_broadcast_campaigns_id'), 'broadcast_campaigns', ['id'], unique=False)
    op.create_table('funnel_landing_pages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('funnel_id', sa.String(length=36), nullable=False),
    sa.Column('seo_title', sa.String(length=255), nullable=True),
    sa.Column('seo_description', sa.String(length=500), nullable=True),
    sa.Column('seo_keywords', sa.String(length=500), nullable=True),
    sa.Column('canonical_url', sa.String(length=1024), nullable=True),
    sa.Column('robots_index', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('robots_follow', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('og_title', sa.String(length=255), nullable=True),
    sa.Column('og_description', sa.String(length=500), nullable=True),
    sa.Column('og_image_url', sa.String(length=1024), nullable=True),
    sa.Column('og_type', sa.String(length=50), nullable=True),
    sa.Column('twitter_card', sa.String(length=50), nullable=True),
    sa.Column('twitter_title', sa.String(length=255), nullable=True),
    sa.Column('twitter_description', sa.String(length=500), nullable=True),
    sa.Column('twitter_image_url', sa.String(length=1024), nullable=True),
    sa.Column('favicon_url', sa.String(length=1024), nullable=True),
    sa.Column('theme_config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['funnel_id'], ['funnels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funnel_landing_pages_funnel_id'), 'funnel_landing_pages', ['funnel_id'], unique=True)
    op.create_index(op.f('ix_funnel_landing_pages_id'), 'funnel_landing_pages', ['id'], unique=False)
    op.create_table('funnel_page_views',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('funnel_id', sa.String(length=36), nullable=False),
    sa.Column('page_type', sa.String(length=20), nullable=False),
    sa.Column('visitor_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['funnel_id'], ['funnels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funnel_page_views_created_at'), 'funnel_page_views', ['created_at'], unique=False)
    op.create_index(op.f('ix_funnel_page_views_funnel_id'), 'funnel_page_views', ['funnel_id'], unique=False)
    op.create_index(op.f('ix_funnel_page_views_id'), 'funnel_page_views', ['id'], unique=False)
    op.create_index(op.f('ix_funnel_page_views_page_type'), 'funnel_page_views', ['page_type'], unique=False)
    op.create_table('gift_automations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('gift_ids', sa.JSON(), nullable=True),
    sa.Column('funnel_id', sa.String(length=36), nullable=True),
    sa.Column('trigger_status', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('max_total_grants', sa.Integer(), nullable=True),
    sa.Column('grants_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('email_subject', sa.Text(), server_default='', nullable=False),
    sa.Column('email_html', sa.Text(), server_default='', nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['funnel_id'], ['funnels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gift_automations_funnel_id'), 'gift_automations', ['funnel_id'], unique=False)
    op.create_index('ix_gift_automations_funnel_status', 'gift_automations', ['funnel_id', 'trigger_status'], unique=False)
    op.create_index(op.f('ix_gift_automations_id'), 'gift_automations', ['id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('source_funnel_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='lead', nullable=False),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('converted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_funnel_id'], ['funnels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'source_funnel_id', name='uq_leads_email_funnel')
    )
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=False)
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_index(op.f('ix_leads_source_funnel_id'), 'leads', ['source_funnel_id'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_table('lucky_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('funnel_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('public_token', sa.String(length=48), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('form_schema', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('success_config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('display_config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('name_field_key', sa.String(length=100), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['funnel_id'], ['funnels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lucky_events_funnel_id'), 'lucky_events', ['funnel_id'], unique=False)
    op.create_index(op.f('ix_lucky_events_id'), 'lucky_events', ['id'], unique=False)
    op.create_index(op.f('ix_lucky_events_public_token'), 'lucky_events', ['public_token'], unique=True)
    op.create_index(op.f('ix_lucky_events_slug'), 'lucky_events', ['slug'], unique=True)
    op.create_index(op.f('ix_lucky_events_status'), 'lucky_events', ['status'], unique=False)
    op.create_table('broadcast_send_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('lead_id', sa.String(length=36), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['broadcast_campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'email', name='uq_broadcast_send_jobs_campaign_email')
    )
    op.create_index(op.f('ix_broadcast_send_jobs_campaign_id'), 'broadcast_send_jobs', ['campaign_id'], unique=False)
    op.create_index('ix_broadcast_send_jobs_campaign_status', 'broadcast_send_jobs', ['campaign_id', 'status'], unique=False)
    op.create_index(op.f('ix_broadcast_send_jobs_id'), 'broadcast_send_jobs', ['id'], unique=False)
    op.create_table('funnel_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('funnel_id', sa.String(length=36), nullable=False),
    sa.Column('lead_id', sa.String(length=36), nullable=True),
    sa.Column('order_code', sa.String(length=13), nullable=False),
    sa.Column('subtotal_amount', sa.Integer(), server_default='0', nullable=False),
    sa.Column('discount_amount', sa.Integer(), server_default='0', nullable=False),
    sa.Column('final_amount', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='PENDING', nullable=False),
    sa.Column('payment_provider', sa.String(length=30), server_default='sepay', nullable=False),
    sa.Column('funnel_title', sa.String(length=255), nullable=False),
    sa.Column('funnel_slug', sa.String(length=255), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('buyer_email', sa.String(length=255), nullable=False),
    sa.Column('buyer_full_name', sa.String(length=255), nullable=True),
    sa.Column('buyer_phone', sa.String(length=50), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fbp', sa.String(length=255), nullable=True),
    sa.Column('fbc', sa.String(length=512), nullable=True),
    sa.Column('client_ip_address', sa.String(length=64), nullable=True),
    sa.Column('client_user_agent', sa.String(length=1024), nullable=True),
    sa.Column('manual_activated_by', sa.String(length=36), nullable=True),
    sa.Column('manual_activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['funnel_id'], ['funnels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manual_activated_by'], ['admin_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funnel_orders_funnel_id'), 'funnel_orders', ['funnel_id'], unique=False)
    op.create_index(op.f('ix_funnel_orders_id'), 'funnel_orders', ['id'], unique=False)
    op.create_index(op.f('ix_funnel_orders_lead_id'), 'funnel_orders', ['lead_id'], unique=False)
    op.create_index(op.f('ix_funnel_orders_order_code'), 'funnel_orders', ['order_code'], unique=True)
    op.create_index(op.f('ix_funnel_orders_status'), 'funnel_orders', ['status'], unique=False)
    op.create_table('funnel_sections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('landing_page_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('html', sa.Text(), server_default='', nullable=False),
    sa.Column('theme_mode', sa.String(length=20), server_default='light', nullable=False),
    sa.Column('section_type', sa.String(length=50), server_default='custom', nullable=False),
    sa.Column('anchor', sa.String(length=80), nullable=True),
    sa.Column('responsive_config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_visible', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['landing_page_id'], ['funnel_landing_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funnel_sections_id'), 'funnel_sections', ['id'], unique=False)
    op.create_index(op.f('ix_funnel_sections_landing_page_id'), 'funnel_sections', ['landing_page_id'], unique=False)
    op.create_index(op.f('ix_funnel_sections_section_type'), 'funnel_sections', ['section_type'], unique=False)
    op.create_table('gift_send_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('lead_id', sa.String(length=36), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['gift_campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'email', name='uq_gift_send_jobs_campaign_email')
    )
    op.create_index(op.f('ix_gift_send_jobs_campaign_id'), 'gift_send_jobs', ['campaign_id'], unique=False)
    op.create_index('ix_gift_send_jobs_campaign_status', 'gift_send_jobs', ['campaign_id', 'status'], unique=False)
    op.create_index(op.f('ix_gift_send_jobs_id'), 'gift_send_jobs', ['id'], unique=False)
    op.create_table('lucky_event_participants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('answers', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('source', sa.String(length=20), server_default='public', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['lucky_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'phone', name='uq_lucky_participant_event_phone')
    )
    op.create_index(op.f('ix_lucky_event_participants_event_id'), 'lucky_event_participants', ['event_id'], unique=False)
    op.create_index(op.f('ix_lucky_event_participants_id'), 'lucky_event_participants', ['id'], unique=False)
    op.create_table('lucky_prizes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['lucky_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lucky_prizes_event_id'), 'lucky_prizes', ['event_id'], unique=False)
    op.create_index(op.f('ix_lucky_prizes_id'), 'lucky_prizes', ['id'], unique=False)
    op.create_table('lucky_winners',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('prize_id', sa.String(length=36), nullable=False),
    sa.Column('participant_id', sa.String(length=36), nullable=False),
    sa.Column('spin_order', sa.Integer(), nullable=False),
    sa.Column('won_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['lucky_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['lucky_event_participants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prize_id'], ['lucky_prizes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'participant_id', name='uq_lucky_winner_event_participant')
    )
    op.create_index(op.f('ix_lucky_winners_event_id'), 'lucky_winners', ['event_id'], unique=False)
    op.create_index(op.f('ix_lucky_winners_id'), 'lucky_winners', ['id'], unique=False)
    op.create_index(op.f('ix_lucky_winners_participant_id'), 'lucky_winners', ['participant_id'], unique=False)
    op.create_index(op.f('ix_lucky_winners_prize_id'), 'lucky_winners', ['prize_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lucky_winners_prize_id'), table_name='lucky_winners')
    op.drop_index(op.f('ix_lucky_winners_participant_id'), table_name='lucky_winners')
    op.drop_index(op.f('ix_lucky_winners_id'), table_name='lucky_winners')
    op.drop_index(op.f('ix_lucky_winners_event_id'), table_name='lucky_winners')
    op.drop_table('lucky_winners')
    op.drop_index(op.f('ix_lucky_prizes_id'), table_name='lucky_prizes')
    op.drop_index(op.f('ix_lucky_prizes_event_id'), table_name='lucky_prizes')
    op.drop_table('lucky_prizes')
    op.drop_index(op.f('ix_lucky_event_participants_id'), table_name='lucky_event_participants')
    op.drop_index(op.f('ix_lucky_event_participants_event_id'), table_name='lucky_event_participants')
    op.drop_table('lucky_event_participants')
    op.drop_index(op.f('ix_gift_send_jobs_id'), table_name='gift_send_jobs')
    op.drop_index('ix_gift_send_jobs_campaign_status', table_name='gift_send_jobs')
    op.drop_index(op.f('ix_gift_send_jobs_campaign_id'), table_name='gift_send_jobs')
    op.drop_table('gift_send_jobs')
    op.drop_index(op.f('ix_funnel_sections_section_type'), table_name='funnel_sections')
    op.drop_index(op.f('ix_funnel_sections_landing_page_id'), table_name='funnel_sections')
    op.drop_index(op.f('ix_funnel_sections_id'), table_name='funnel_sections')
    op.drop_table('funnel_sections')
    op.drop_index(op.f('ix_funnel_orders_status'), table_name='funnel_orders')
    op.drop_index(op.f('ix_funnel_orders_order_code'), table_name='funnel_orders')
    op.drop_index(op.f('ix_funnel_orders_lead_id'), table_name='funnel_orders')
    op.drop_index(op.f('ix_funnel_orders_id'), table_name='funnel_orders')
    op.drop_index(op.f('ix_funnel_orders_funnel_id'), table_name='funnel_orders')
    op.drop_table('funnel_orders')
    op.drop_index(op.f('ix_broadcast_send_jobs_id'), table_name='broadcast_send_jobs')
    op.drop_index('ix_broadcast_send_jobs_campaign_status', table_name='broadcast_send_jobs')
    op.drop_index(op.f('ix_broadcast_send_jobs_campaign_id'), table_name='broadcast_send_jobs')
    op.drop_table('broadcast_send_jobs')
    op.drop_index(op.f('ix_lucky_events_status'), table_name='lucky_events')
    op.drop_index(op.f('ix_lucky_events_slug'), table_name='lucky_events')
    op.drop_index(op.f('ix_lucky_events_public_token'), table_name='lucky_events')
    op.drop_index(op.f('ix_lucky_events_id'), table_name='lucky_events')
    op.drop_index(op.f('ix_lucky_events_funnel_id'), table_name='lucky_events')
    op.drop_table('lucky_events')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_source_funnel_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_gift_automations_id'), table_name='gift_automations')
    op.drop_index('ix_gift_automations_funnel_status', table_name='gift_automations')
    op.drop_index(op.f('ix_gift_automations_funnel_id'), table_name='gift_automations')
    op.drop_table('gift_automations')
    op.drop_index(op.f('ix_funnel_page_views_page_type'), table_name='funnel_page_views')
    op.drop_index(op.f('ix_funnel_page_views_id'), table_name='funnel_page_views')
    op.drop_index(op.f('ix_funnel_page_views_funnel_id'), table_name='funnel_page_views')
    op.drop_index(op.f('ix_funnel_page_views_created_at'), table_name='funnel_page_views')
    op.drop_table('funnel_page_views')
    op.drop_index(op.f('ix_funnel_landing_pages_id'), table_name='funnel_landing_pages')
    op.drop_index(op.f('ix_funnel_landing_pages_funnel_id'), table_name='funnel_landing_pages')
    op.drop_table('funnel_landing_pages')
    op.drop_index(op.f('ix_broadcast_campaigns_id'), table_name='broadcast_campaigns')
    op.drop_index(op.f('ix_broadcast_campaigns_funnel_id'), table_name='broadcast_campaigns')
    op.drop_table('broadcast_campaigns')
    op.drop_index(op.f('ix_order_discounts_order_id'), table_name='order_discounts')
    op.drop_index(op.f('ix_order_discounts_id'), table_name='order_discounts')
    op.drop_index(op.f('ix_order_discounts_discount_id'), table_name='order_discounts')
    op.drop_table('order_discounts')
    op.drop_index(op.f('ix_funnels_status'), table_name='funnels')
    op.drop_index(op.f('ix_funnels_slug'), table_name='funnels')
    op.drop_index(op.f('ix_funnels_product_id'), table_name='funnels')
    op.drop_index(op.f('ix_funnels_id'), table_name='funnels')
    op.drop_index(op.f('ix_funnels_capture_token'), table_name='funnels')
    op.drop_table('funnels')
    op.drop_index(op.f('ix_discount_scopes_owner_id'), table_name='discount_scopes')
    op.drop_index(op.f('ix_discount_scopes_id'), table_name='discount_scopes')
    op.drop_index(op.f('ix_discount_scopes_discount_id'), table_name='discount_scopes')
    op.drop_table('discount_scopes')
    op.drop_index(op.f('ix_discount_default_activations_owner_id'), table_name='discount_default_activations')
    op.drop_index(op.f('ix_discount_default_activations_id'), table_name='discount_default_activations')
    op.drop_index(op.f('ix_discount_default_activations_discount_id'), table_name='discount_default_activations')
    op.drop_table('discount_default_activations')
    op.drop_index(op.f('ix_url_redirects_source_path'), table_name='url_redirects')
    op.drop_index(op.f('ix_url_redirects_is_active'), table_name='url_redirects')
    op.drop_index(op.f('ix_url_redirects_id'), table_name='url_redirects')
    op.drop_table('url_redirects')
    op.drop_index(op.f('ix_products_type'), table_name='products')
    op.drop_index(op.f('ix_products_status'), table_name='products')
    op.drop_index(op.f('ix_products_source_id'), table_name='products')
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_media_assets_uploaded_by'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_object_key'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_kind'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_id'), table_name='media_assets')
    op.drop_table('media_assets')
    op.drop_index(op.f('ix_gift_grants_id'), table_name='gift_grants')
    op.drop_index(op.f('ix_gift_grants_gift_id'), table_name='gift_grants')
    op.drop_index('ix_gift_grants_email_status', table_name='gift_grants')
    op.drop_index('ix_gift_grants_email', table_name='gift_grants')
    op.drop_table('gift_grants')
    op.drop_index('ix_email_templates_scope_owner', table_name='email_templates')
    op.drop_index(op.f('ix_email_templates_id'), table_name='email_templates')
    op.drop_table('email_templates')
    op.drop_index(op.f('ix_discounts_is_active'), table_name='discounts')
    op.drop_index(op.f('ix_discounts_id'), table_name='discounts')
    op.drop_index(op.f('ix_discounts_code'), table_name='discounts')
    op.drop_table('discounts')
    op.drop_index(op.f('ix_site_settings_key'), table_name='site_settings')
    op.drop_index(op.f('ix_site_settings_id'), table_name='site_settings')
    op.drop_table('site_settings')
    op.drop_index(op.f('ix_gifts_id'), table_name='gifts')
    op.drop_table('gifts')
    op.drop_index('ix_gift_campaigns_status', table_name='gift_campaigns')
    op.drop_index(op.f('ix_gift_campaigns_id'), table_name='gift_campaigns')
    op.drop_table('gift_campaigns')
    op.drop_index(op.f('ix_admin_users_id'), table_name='admin_users')
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
